[custom]

;acl4SSR规则-V7

;exclude_remarks=(剩余流量|流量|过期|到期|时间|官网|本站|用户|续费|邮箱|订阅|套餐|产品|平台|过滤)

ruleset=🏠 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🏠 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list

ruleset=🚀 出口节点,https://raw.githubusercontent.com/Williamyb97/ACL4SSR/main/My_rule/my_Proxy.list

ruleset=🚫 广告过滤,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🚫 广告过滤,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

ruleset=🏠 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🏠 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list

ruleset=🤖 智能专区,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=🤖 智能专区,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list

ruleset=📺 国内服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📺 国内服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 国内服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=📺 国内服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=📺 国内服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=📺 国内服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=📺 国内服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list

ruleset=🚀 出口节点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 出口节点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 出口节点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list

ruleset=🏠 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🏠 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=🏠 国内直连,[]GEOIP,LAN
ruleset=🏠 国内直连,[]GEOIP,CN

ruleset=🌐 未知流量,[]FINAL

custom_proxy_group=🚀 出口节点`select`[]♻️ 延迟优选`.*
custom_proxy_group=🤖 智能专区`select`(GPT|Gemini|Chat|OpenAI|Claude|AI|gpt|gemini|chat|openai|claude|ai)`[]🚀 出口节点
custom_proxy_group=🌐 未知流量`select`[]DIRECT`[]🚀 出口节点
custom_proxy_group=🚫 广告过滤`select`[]REJECT`[]DIRECT
custom_proxy_group=🏠 国内直连`select`[]DIRECT
custom_proxy_group=📺 国内服务`select`[]DIRECT
custom_proxy_group=♻️ 延迟优选`url-test`.*`http://www.gstatic.com/generate_204`300,,50

enable_rule_generator=true
overwrite_original_rules=true






